import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  loginContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#05668D',
  },
  chatContainer: {
    flex: 1,
    backgroundColor: '#05668D',
  },
  inputContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  loginInput: {
    margin: 15,
    height: 40,
    width: 200,
    borderColor: '#fb8357',
    borderWidth: 1,
    alignItems: 'center',
    color: '#EDF2F4',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#fb8357',
    height: 40,
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    borderRadius: 10,
  },
  chatInput: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    margin: 10,
    paddingLeft: 10,
    borderColor: '#fb8357',
    borderWidth: 1,
    alignItems: 'center',
    color: '#EDF2F4',
    textAlign: 'left',
  },
  message: {
    backgroundColor: '#fb8357',
    padding: 8,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  myMessage: {
    backgroundColor: '#222222',
    padding: 8,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 20,
    alignSelf: 'flex-end',
  },
  nicknameText: {
    color: '#FB8D62',
    fontWeight: 'bold',
  },
  text: {
    color: '#EDF2F4',
  },
  icon: {
    height: 40,
    width: 40,
    alignSelf: 'center',
  },
});
